# -*- coding: utf-8 -*-
"""Project 13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10LkBWOhROQfv5OfEL4BmaWV73mYy5iKt
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.datasets import make_blobs
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV
from matplotlib import style
style.use('dark_background')

x,y  =  make_blobs(n_samples = 1000,n_features = 3,centers = 3,cluster_std = 4,random_state = 42)
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state  = 42)
sc = StandardScaler()
x_train =  sc.fit_transform(x_train)
x_test = sc.transform(x_test)
knn  =  KNeighborsClassifier()
knn.fit(x_train,y_train)

np.unique(y_train)

plt.figure(figsize = (7,7))
plt.scatter(x_train[y_train  ==0,0],x_train[y_train ==0,1],s = 15)
plt.scatter(x_train[y_train ==1,0],x_train[y_train==1,1],s = 15)
plt.scatter(x_train[y_train==2,0],x_train[y_train==2,1],s = 15)
plt.show()

plt.figure(figsize  =  (5,5))
plt.scatter(x_test[y_test == 0,0],x_test[y_test==0,1],s = 15,color = 'yellow')
plt.scatter(x_test[y_test==1,0],x_test[y_test==1,1],s=15,color = 'red')
plt.scatter(x_test[y_test ==2,0],x_test[y_test==2,1],s = 15,color = 'blue')
plt.show()

prediction  = knn.predict(x_test)
accuracy = np.mean(prediction  ==y_test)
accuracy

plt.scatter(x_test[prediction==0,0],x_test[prediction==0,1],s = 15,color = 'yellow')
plt.scatter(x_test[prediction==1,0],x_test[prediction==1,1],s = 15,color = 'red')
plt.scatter(x_test[prediction==2,0] , x_test[prediction==2,1],s = 15,color = 'blue')

error_rate  =[]
for i in range(1,30):
  knn1   = KNeighborsClassifier(n_neighbors = i)
  knn1.fit(x_train,y_train)
  pred  = knn1.predict(x_test)
  current_accuracy =  np.mean(pred ==y_test)
  error_rate_value =  1-current_accuracy
  error_rate.append(error_rate_value)



plt.plot(range(1,30),error_rate,marker = 'o',markerfacecolor = 'blue',markeredgecolor = 'red',lw   = 1.5)

knn2  =  KNeighborsClassifier(n_neighbors =  20)
knn2.fit(x_train,y_train)
prediction2  =  knn2.predict(x_test)
accuracy3 = np.mean(prediction2 ==y_test)
accuracy3

cv =  KFold(n_splits  =  5,shuffle = True , random_state  =  42)
model  =  KNeighborsClassifier()
parameters = {'n_neighbors':[np.arange(1,30)]}
grid  =  GridSearchCV(model, parameters,cv = cv)
grid.fit(x_train,y_train)
grid.best_params_









